#!/usr/bin/python

import sys
import re
import io
import typing
import unittest


class Bakshu:
    FindPattern = r'''(?x)
      (?P<ascii> [\x00-\x7F]+)
    | (?P<mb>   [^\x00-\x7F]+)
    '''

    def __init__(self, string: str, window: int = 3):
        self.__window: int = window
        self.__str: str = ''

        for match in re.finditer(self.FindPattern, string):
            self.__str += self.__process(match)

    def __process(self, match: re.Match) -> str:
        if match.group('ascii'):
            return match.group('ascii')

        mb_str = match.group('mb')
        if len(mb_str) <= self.__window:
            return ' '.join(['', mb_str, ''])
        grams = [mb_str[i:(i + self.__window)] for i in range(len(mb_str) - (self.__window - 1))]
        return ' '.join([''] + grams + [''])

    def print(self):
        print(self.__str, end='')

    def string(self) -> str:
        return self.__str


class TestBakshu(unittest.TestCase):
    Tests = {
        "abc あいうえお def": "abc  あいう いうえ うえお  def",
        "abcあいうえおdef": "abc あいう いうえ うえお def",
        "abcあいう\nえおdef": "abc あいう \n えお def",
        "abcあいうdefえおghi": "abc あいう def えお ghi",
        "abcあいうdef": "abc あいう def",
        "あいうえお": " あいう いうえ うえお ",
        "a b c": "a b c",
        "あい": " あい ",
        "a": "a",
    }

    def test(self):
        for t, e in self.Tests.items():
            self.assertEqual(Bakshu(t).string(), e)


if __name__ == '__main__':
    if sys.stdin.isatty():
        unittest.main()
    else:
        typing.cast(io.TextIOWrapper, sys.stdin).reconfigure(encoding='utf-8', errors='ignore')
        for buf in sys.stdin.readlines():
            Bakshu(buf).print()
