#!/bin/bash

targets=(
	"good:$HOME/Maildir/.Archives"
	"junk:$HOME/Maildir/.Junk"
)
max_rounds=10

# Ryoca default; CHANGE IF NEEDED
fileprefix="$HOME/.ryoca"

for round in $(seq 1 $max_rounds); do
	echo "[Round $round]"
	learned=0

	for target in "${targets[@]}"; do
		for mail in $(find "${target#*:}/cur" -type f | sort); do

			# Skip obvious spams; CHANGE OR DISABLE IF NEEDED
			grep -E -q 'dmarc=fail \(p=(reject|quarantine)' < "$mail" && continue

			if ryoca --fileprefix="$fileprefix" --learn="${target%:*}" --verbose < "$mail" 2>&1 >/dev/null | grep -E -q '^learn '; then
				((learned++))
				printf "\r%${COLUMNS}s\r[%d] %s" '' $learned "$mail"
			fi
		done
	done

	echo
	[ $learned -eq 0 ] && break
done

# vim: tabstop=4 shiftwidth=4
